language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

before_install:
- yes | sdkmanager "platforms;android-27"

install:
- nvm install 8
- npm install -g ionic cordova
- npm install

script:
- npm run android:build # implies web build in www/ dir

deploy:
  # deploy web build to gh-pages branch
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    #on:
    #  tags: true
    local_dir: www

  # deploy android project for fdroid builds
  - provider: script
    script: bash tools/deploy-fdroid.sh
    skip-cleanup: true
    #on:
    #  tags: true
