language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

before_install:
- yes | sdkmanager "platforms;android-27" # accept android licenses

install:
- nvm install 12
- npm install -g ionic cordova
- npm install

script:
- npm run android:build # implies web build in www/ dir

before_deploy: "cp platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk sensebox_blockly_${TRAVIS_TAG}.apk"

deploy:
  # deploy web build to gh-pages branch
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      tags: true
    local_dir: www

  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "sensebox_blockly_${TRAVIS_TAG}.apk"
    skip_cleanup: true
    on:
      tags: true
