language: node_js
node_js:
- "8"

branches:
  only:
  - master

before_script:
- npm install

script:
- npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  on:
    tags: true
  local_dir: www
